//: https://github.com/jsdom/cssstyle/issues/182
packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/lit/**'
  - 'examples/svelte/**'
catalog:
  '@analogjs/vite-plugin-angular': ^1.17.1
  '@analogjs/vitest-angular': ^1.17.1
  '@angular/common': ^20.0.0
  '@angular/compiler': ^20.0.0
  '@angular/compiler-cli': ^20.0.0
  '@angular/core': ^20.0.0
  '@angular/platform-browser': ^20.0.0
  '@angular/platform-browser-dynamic': ^20.0.0
  '@eslint-react/eslint-plugin': ^1.52.2
  '@solidjs/testing-library': ^0.8.10
  '@sveltejs/package': ^2.3.11
  '@sveltejs/vite-plugin-svelte': ^5.1.0
  '@tanstack/config': 0.20.0
  '@tanstack/devtools': 0.1.1
  '@tanstack/devtools-event-': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-bus-plugin@11
  '@tanstack/devtools-event-c': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/devtools-event-cl': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/devtools-event-cli': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/devtools-event-clie': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/devtools-event-clien': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/devtools-event-client': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  '@tanstack/react--devtools': 0.2.0
  '@tanstack/react-devtools': https://pkg.pr.new/TanStack/devtools/@tanstack/react-devtools@11
  '@tanstack/react-form': ^1.17.0
  '@tanstack/react-form-devtools': 0.2.0
  '@tanstack/react-start': ^1.130.10
  '@tanstack/react-store': ^0.7.3
  '@tanstack/solid-store': ^0.7.3
  '@tanstack/store': ^0.7.2
  '@tanstack/svelte-store': ^0.7.3
  '@testing-library/angular': ^17.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/svelte': ^5.2.8
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  '@types/node': ^24.1.0
  '@types/react': ^19.0.7
  '@types/react-dom': ^19.0.3
  '@vitejs/plugin-react': ^4.5.2
  '@vitest/coverage-istanbul': ^3.2.3
  arktype: ^2.1.20
  babel-plugin-react-compiler: 19.0.0-beta-ebf51a3-20250411
  decode-formdata: ^0.9.0
  devalue: ^5.1.1
  eslint: 9.32.0
  eslint-plugin-react-compiler: 19.0.0-beta-ebf51a3-20250411
  eslint-plugin-react-hooks: ^5.2.0
  jsdom: ^26.1.0
  knip: ^5.61.0
  lit: ^3.3.0
  markdown-link-extractor: ^4.0.2
  ng-packagr: ^20.0.0
  nx: 21.3.11
  premove: ^4.0.0
  prettier: ^3.6.2
  publint: ^0.3.12
  react: ^19.0.0
  react-dom: ^19.0.0
  sherif: ^1.5.0
  solid-js: ^1.9.7
  svelte: ^5.34.3
  svelte-check: ^4.2.1
  tinyglobby: ^0.2.14
  tslib: ^2.8.1
  typescript: 5.8.2
  typescript54: npm:typescript@5.8.3
  typescript55: npm:typescript@5.8.3
  typescript56: npm:typescript@5.8.3
  typescript57: npm:typescript@5.8.3
  valibot: ^1.1.0
  vite: ^7.0.6
  vite-plugin-solid: ^2.11.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.3
  zod: ^3.25.76
  zone.js: 0.15.1
catalogs:
  conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event1
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventm:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmc:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-c
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmcl:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-cl
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmcli:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-cli
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclie:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-clie
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclien:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-clien
  conflicts_conflicts_@tanstack/devtools-event-bus-plugin_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmevent1_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclient:
    '@tanstack/devtools-event-bus-plugin': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client
  conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11:
    '@tanstack/devtools-event-client': https://pkg.pr.new/TanStack/devtools/@tanstack/devtools-event-client@11
  conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b:
    '@tanstack/react-devtools': https://pkg.pr.new/TanStack/devtools/@tanstack/react-devtools@0a0219b
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_:
    '@tanstack/react-devtools': ''
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_a:
    '@tanstack/react-devtools': '@'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_at:
    '@tanstack/react-devtools': '@t'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_ata:
    '@tanstack/react-devtools': '@ta'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atan:
    '@tanstack/react-devtools': '@tan'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atans:
    '@tanstack/react-devtools': '@tans'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanst:
    '@tanstack/react-devtools': '@tanst'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atansta:
    '@tanstack/react-devtools': '@tansta'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstac:
    '@tanstack/react-devtools': '@tanstac'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstacl:
    '@tanstack/react-devtools': '@tanstacl'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack:
    '@tanstack/react-devtools': '@tanstack'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/:
    '@tanstack/react-devtools': '@tanstack/'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/r:
    '@tanstack/react-devtools': '@tanstack/r'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/re:
    '@tanstack/react-devtools': '@tanstack/re'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/rea:
    '@tanstack/react-devtools': '@tanstack/rea'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reac:
    '@tanstack/react-devtools': '@tanstack/reac'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/react:
    '@tanstack/react-devtools': '@tanstack/react'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactm:
    '@tanstack/react-devtools': '@tanstack/react-'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmd:
    '@tanstack/react-devtools': '@tanstack/react-d'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmde:
    '@tanstack/react-devtools': '@tanstack/react-de'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmdev:
    '@tanstack/react-devtools': '@tanstack/react-dev'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmdevt:
    '@tanstack/react-devtools': '@tanstack/react-devt'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmdevto:
    '@tanstack/react-devtools': '@tanstack/react-devto'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmdevtoo:
    '@tanstack/react-devtools': '@tanstack/react-devtoo'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmdevtool:
    '@tanstack/react-devtools': '@tanstack/react-devtool'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_atanstack/reactmdevtools:
    '@tanstack/react-devtools': '@tanstack/react-devtools'
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_tanstack/devtoolsmeventmclienta11:
    '@tanstack/devtools-event-client': tanstack/devtools-event-client@11
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_tanstack/devtoolsmeventmclienta1:
    '@tanstack/devtools-event-client': tanstack/devtools-event-client@1
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_tanstack/devtoolsmeventmclienta:
    '@tanstack/devtools-event-client': tanstack/devtools-event-client@
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_tanstack/devtoolsmeventmclient:
    '@tanstack/devtools-event-client': tanstack/devtools-event-client
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_atanstack/devtoolsmeventmclient:
    '@tanstack/devtools-event-client': '@tanstack/devtools-event-client'
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_:atanstack/reactmdevtools:
    '@tanstack/react-devtools': :@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_filatanstack/reactmdevtools:
    '@tanstack/react-devtools': fil@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_fiatanstack/reactmdevtools:
    '@tanstack/react-devtools': fi@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_fatanstack/reactmdevtools:
    '@tanstack/react-devtools': f@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_ile:atanstack/reactmdevtools:
    '@tanstack/react-devtools': ile:@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_ileatanstack/reactmdevtools:
    '@tanstack/react-devtools': ile@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_ilatanstack/reactmdevtools:
    '@tanstack/react-devtools': il@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_iatanstack/reactmdevtools:
    '@tanstack/react-devtools': i@tanstack/react-devtools
  conflicts_conflicts_@tanstack/react-devtools_https://pkg_pr_new/TanStack/devtools/atanstack/reactmdevtoolsa0a0219b_0_2_0:
    '@tanstack/react-devtools': 0.2.0
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_:
    '@tanstack/devtools-event-client': ''
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_0_2_0:
    '@tanstack/devtools-event-client': 0.2.0
  conflicts_conflicts_@tanstack/devtools-event-client_https://pkg_pr_new/TanStack/devtools/atanstack/devtoolsmeventmclienta11_h0_2_0:
    '@tanstack/devtools-event-client': ^0.2.0
  conflicts_@tanstack/react-form-devtools_h1_17_0:
    '@tanstack/react-form-devtools': ^1.17.0
overrides:
  cssstyle: 4.4.0
