cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - packages/**
  - examples/angular/**
  - examples/react/**
  - examples/preact/**
  - examples/solid/**
  - examples/vue/**
  - examples/lit/**
  - examples/svelte/**
