packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/lit/**'
  - 'examples/svelte/**'
catalog:
  '@tanstack/react-start': ^1.131.27
  '@tanstack/react-store': ^0.7.4
  '@types/react': ^19.0.7
  '@types/react-dom': ^19.0.3
  '@vitejs/plugin-react': ^4.7.0
  decode-formdata: ^0.9.0
  devalue: ^5.3.2
  eslint-plugin-react-compiler: 19.0.0-beta-ebf51a3-20250411
  react: ^19.0.0
  react-dom: ^19.0.0
  vite: ^7.1.3
