packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/lit/**'
  - 'examples/svelte/**'
catalog:
  '@tanstack/store': ^0.7.2
  arktype: ^2.1.20
  valibot: ^1.1.0
  zod: ^3.25.76
