//: https://github.com/jsdom/cssstyle/issues/182
packages:
  - 'packages/**'
  - 'examples/angular/**'
  - 'examples/react/**'
  - 'examples/solid/**'
  - 'examples/vue/**'
  - 'examples/lit/**'
  - 'examples/svelte/**'
catalog:
  '@eslint-react/eslint-plugin': ^1.53.1
  '@solidjs/testing-library': ^0.8.10
  '@tanstack/config': 0.20.2
  '@tanstack/devtools-event-client': ^0.3.0
  '@tanstack/devtools-ui': ^0.3.5
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-form': workspace:*
  '@tanstack/react-start': ^1.131.50
  '@tanstack/react-store': ^0.7.7
  '@tanstack/solid-store': ^0.7.7
  '@tanstack/store': ^0.7.7
  '@testing-library/jest-dom': ^6.8.0
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  '@types/node': ^24.1.0
  '@types/react': ^19.0.7
  '@types/react-dom': ^19.0.3
  '@vitejs/plugin-react': ^4.7.0
  '@vitest/coverage-istanbul': ^3.2.4
  arktype: ^2.1.22
  clsx: ^2.1.1
  dayjs: ^1.11.18
  decode-formdata: ^0.9.0
  devalue: ^5.3.2
  eslint: 9.36.0
  eslint-plugin-react-compiler: 19.0.0-beta-ebf51a3-20250411
  eslint-plugin-react-hooks: ^5.2.0
  goober: ^2.1.16
  jsdom: ^26.1.0
  knip: ^5.63.1
  markdown-link-extractor: ^4.0.2
  nx: 21.5.3
  premove: ^4.0.0
  prettier: ^3.6.2
  publint: ^0.3.13
  react: ^19.0.0
  react-dom: ^19.0.0
  sherif: ^1.6.1
  solid-js: ^1.9.9
  tinyglobby: ^0.2.15
  typescript: 5.8.2
  typescript54: npm:typescript@5.9.2
  typescript55: npm:typescript@5.9.2
  typescript56: npm:typescript@5.9.2
  typescript57: npm:typescript@5.9.2
  valibot: ^1.1.0
  vite: ^7.1.6
  vite-plugin-solid: ^2.11.8
  vitest: ^3.2.4
  zod: ^3.25.76
overrides:
  cssstyle: 4.6.0
