cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - packages/**
  - examples/angular/**
  - examples/react/**
  - examples/preact/**
  - examples/solid/**
  - examples/vue/**
  - examples/lit/**
  - examples/svelte/**

allowBuilds:
  # root dependency
  nx: true
  unrs-resolver: false # not directly required for build
  esbuild: true

  # nx, @vitejs/plugin-react-swc, terser-webpack-plugin
  '@swc/core': true

  # @angular/build
  '@parcel/watcher': false # optional dep of @angular/build
  lmdb: false # optional dep of @angular/build
  msgpackr-extract: false # optional dep of @angular/build

  # @tanstack/vue-store
  vue-demi: false # only required for vue 2 support

  # nextJs
  sharp: false # not directly required for build
