name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [main, alpha, beta]
  workflow_dispatch:
    inputs:
      generate-docs:
        description: 'Generate docs'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    if: ${{ !contains(github.event.head_commit.message, 'apply automated fixes') }}
    name: autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Tools
        uses: TanStack/config/.github/setup@99d23c6212f36eff17d30a21e58da77f55a4cfe9 # main
      - name: Fix formatting
        run: pnpm format
      - name: Generate Docs
        if: ${{ github.event_name == 'push' || github.event.inputs.generate-docs == true }}
        run: pnpm generate-docs
      - name: Apply fixes
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          commit-message: 'ci: apply automated fixes and generate docs'
